---
# https://github.com/polybar/polybar/wiki/Compiling
- name: Update repository cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install dependencies
  become: true
  ansible.builtin.package:
    name:
      - build-essential
      - git
      - cmake
      - cmake-data
      - pkg-config
      - libuv1-dev
      - libcairo2-dev
      - libxcb1-dev
      - libxcb-util0-dev
      - libxcb-randr0-dev
      - libxcb-composite0-dev
      - python3-xcbgen
      - xcb-proto
      - libxcb-image0-dev
      - libxcb-ewmh-dev
      - libxcb-icccm4-dev
    state: present

- name: "Download polybar-{{ polybar.version }}.tar.gz"
  become: false
  ansible.builtin.get_url:
    url: "https://github.com/polybar/polybar/releases/download/{{ polybar.version }}/polybar-{{ polybar.version }}.tar.gz"
    dest: "/tmp/polybar-{{ polybar.version }}.tar.gz"
    mode: '0644'

- name: "Extract polybar-{{ polybar.version }}.tar.gz"
  become: false
  ansible.builtin.unarchive:
    remote_src: true
    src: "/tmp/polybar-{{ polybar.version }}.tar.gz"
    dest: "/tmp/"

- name: Build polybar
  become: false
  ansible.builtin.command: ./build.sh -f --auto
  args:
    chdir: "/tmp/polybar-{{ polybar.version }}"
    creates: /usr/local/bin/polybar
