---
- name: Update pacman cache
  become: true
  community.general.pacman:
    update_cache: true
  changed_when: false
  when: ansible_os_family == 'Archlinux'

- name: Install all base packages
  become: true
  community.general.pacman:
    name: "{{ base_packages }}"
    state: present
  when: ansible_os_family == 'Archlinux'
