---
- name: Install yay for easy AUR package installs
  ansible.builtin.include_role:
    name: jahrik.yay
  when: ansible_os_family == 'Archlinux'

- name: Install alacritty
  ansible.builtin.include_role:
    name: jahrik.alacritty

- name: Install and configure i3-gaps
  ansible.builtin.include_role:
    name: jahrik.i3_gaps

- name: Install and configure polybar
  ansible.builtin.include_role:
    name: jahrik.polybar

- name: Install urxvt
  ansible.builtin.include_role:
    name: jahrik.urxvt

- name: Install and configure conky
  ansible.builtin.include_role:
    name: jahrik.conky

- name: Install and configure zsh and set as default user shell
  ansible.builtin.include_role:
    name: jahrik.zsh

- name: Install vim, vundle, and plugins
  ansible.builtin.include_role:
    name: jahrik.vim

- name: Install nvim, packer, lsp, and plugins
  ansible.builtin.include_role:
    name: jahrik.nvim
