---
- name: Clone yay from github
  become: false
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    version: master
    update: true
  tags:
    - yay

- name: Build and install yay with makepkg
  become: false
  ansible.builtin.command: makepkg --noconfirm -si
  args:
    chdir: /tmp/yay
    creates: /usr/bin/yay
  tags:
    - yay
