---
- name: Install requirements
  become: true
  community.general.pacman:
    update_cache: true
    name:
      - fd
      - fontconfig
      - nodejs
      - npm
      - python-pynvim
      - python-setuptools
      - python-virtualenv
      - ripgrep
      - unzip
    state: present
