---
- name: Install requirements
  become: true
  ansible.builtin.package:
    name:
      - curl
      - dirmngr
      - fd-find
      - fontconfig
      - git
      - python3-setuptools
      - python3-virtualenv
      - ripgrep
      - unzip
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Install python3-neovim if Ubuntu 18
  become: true
  ansible.builtin.package:
    name: python3-neovim
  when:
    - "ansible_distribution_major_version | int >= 18"
    - "ansible_distribution_major_version | int < 20"

- name: Install python3-pynvim
  become: true
  ansible.builtin.package:
    name: python3-pynvim
  when: "ansible_distribution_major_version | int >= 20"

- name: Add neovim-ppa
  become: true
  ansible.builtin.apt_repository:
    repo: 'ppa:neovim-ppa/unstable'
    update_cache: true

- name: Install the gpg key for nodejs LTS
  become: true
  ansible.builtin.apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
    state: present

- name: Install the nodejs 20 LTS repos
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_20.x nodistro main"
    state: present
    update_cache: true

- name: Install nodejs
  become: true
  ansible.builtin.apt:
    name: nodejs
    state: present

- name: Gather package facts
  become: true
  ansible.builtin.package_facts:
    manager: auto

# Ubuntu 20.04 comes with an old version of neovim
- name: Uninstall old versions of neovim if < 0.6
  become: true
  ansible.builtin.apt:
    name: neovim
    state: absent
  when:
    - "'neovim' in ansible_facts.packages"
    - "ansible_facts.packages.neovim[0].version is version('0.6.0', '<')"
