---
- name: Install dependencies
  become: true
  community.general.pacman:
    name:
      - base-devel
      - git
    state: present

- name: Clone yay from github
  become: false
  ansible.builtin.git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    version: master
    update: true
  tags:
    - yay

- name: makepkg --noconfirm -si
  become: false
  ansible.builtin.command: makepkg --noconfirm -si
  args:
    chdir: /tmp/yay
    creates: /usr/bin/yay
  tags:
    - yay

- name: Install packages from AUR
  become: true
  yay:
    name: "{{ item }}"
    state: present
  loop: "{{ aur_packages }}"
  when: aur_packages
