---
- name: Uninstall vim
  become: true
  ansible.builtin.package:
    name:
      - vim-syntastic
      - vim
    state: absent
  tags:
    - vim

- name: Backup ~/.config/vim to /tmp/vim
  become: false
  ansible.posix.synchronize:
    src: ~/.config/vim/
    dest: /tmp/vim

- name: Remove ~/.config/vim directory
  become: false
  ansible.builtin.file:
    path: "~/.config/vim/"
    state: absent
  tags:
    - vim

- name: Backup ~/.vimrc to /tmp/vim/.vimrc
  become: false
  ansible.posix.synchronize:
    src: ~/.vimrc
    dest: /tmp/vim/.vimrc

- name: Remove ~/.vimrc
  become: false
  ansible.builtin.file:
    path: "~/.vimrc"
    state: absent
  tags:
    - vim
