---

- name: Install docker packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - docker-compose
    - docker-machine
  tags: [ "docker" ]

- name: Verify docker group exists
  group:
    name: docker
    state: present
  tags: [ "docker" ]

- name: Add user to docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: yes
  tags: [ "docker" ]

- name: Configuring loop module
  template:
    src: "loop.conf.j2"
    dest: "/etc/modules-load.d/loop.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - modprobe loop
  tags: [ "docker" ]

- name: start docker daemon
  systemd:
    name: docker.service
    state: started
    daemon_reload: yes
    enabled: yes
  tags: [ "docker" ]
