---
- name: Install Sway
  become: true
  ansible.builtin.apt:
    name:
      - sway
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags:
    - sway

- name: Install sway extras
  become: true
  ansible.builtin.package:
    name:
      - dunst
      - waybar
    state: present
  tags:
    - sway
