---
- name: Install dependencies
  become: true
  ansible.builtin.package:
    name:
      - dirmngr
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add ppa:aslatter/ppa
  become: true
  ansible.builtin.apt_repository:
    repo: 'ppa:aslatter/ppa'
    update_cache: true
