---
- name: Uninstall alacritty
  become: true
  ansible.builtin.package:
    name:
      - alacritty
    state: absent

- name: Destroy ~/.config/alacritty directory
  become: false
  ansible.builtin.file:
    path: ~/.config/alacritty
    state: absent
