---
name: CICD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v7
      - name: Set up Python 3
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: '3.12'
      - name: Install test dependencies
        run: uv sync
      - name: Install Galaxy requirements
        run: uv run ansible-galaxy role install -r requirements.yml
      - name: Lint code
        run: uv run yamllint .
      - name: Ansible lint
        run: uv run ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v7
      - name: Set up Python 3
        uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: '3.12'
      - name: Install test dependencies
        run: uv sync
      - name: Run Molecule
        run: uv run molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

  release:
    name: Release
    needs: [lint, molecule]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
          git_branch: main
